### ISSUE TITLE
MATLink`mEngine` is (incorrectly) added to context path

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#1]
Currently `MATLink`mEngine``  is added to `$ContextPath` because `BeginPackage[]` (not `Begin[]`) is used in `template.c`.

We need to figure out how to change this to `Begin[]` and keep the package working.

Also need to ensure that `engEngine[]` returns type wrapper symbols in the `MATLink`mEngine`` context.

**Comment by rsmenon** [comment]
This was fixed during the complete rewrite of the Engine in C++
