### ISSUE TITLE
(Howto?)Evaluating Mathematica from Matlab using Matlink

### ISSUE THREAD

**Issue by goosterw** [rsmenon/MATLink#101]
Hey Guys,

I found a lot of information and examples on how to communicate from Mathematica to Matlab, but nothing for the other way around. I would like to run my scripts/functions in Matlab, send data to Mathematica, let Mathematica calculate some stuff, and send the information back to Matlab. (http://matlink.org/ is not clear about this issue.)

I searched for this question but only found a question from 2015 and it was about the Matlab Symbolic package which didn't help me.
Could someone explain how this would work?

Thanks, Gerard

**Comment by szhorvat** [comment]
Hello, this is not currently possible with MATLink. See e.g. #99   MATLink allows for calling MATLAB from Mathematica, but not the reverse.

There are packages for the reverse, but they seem unmaintained and I never tried them: https://www.mathworks.com/matlabcentral/fileexchange/6044-mathematica-symbolic-toolbox-for-matlab-version-2-0

If you are on Windows, you can connect a Mathematica session to a MATLAB one in such a way that both remain interactive. See here: https://mathematica.stackexchange.com/a/69937/12

With this feature, you can work in MATLAB, then take control of the MATLAB session from Mathematica, retrieve the data, do the processing, send the result back, then continue working in MATLAB.  You would need to do this switch manually, as MATLink only allows Mathematica to control MATLAB programmatically. It does not allow MATLAB to control Mathematica.
