### ISSUE TITLE
OpenMATLAB works, but I don't see matlab anywhere?

### ISSUE THREAD

**Issue by andrewmccullough1** [rsmenon/MATLink#104]
I am using a windows 64-bit system with MATLAB R2019b(64-bit) and Mathematica 12(64-bit).  I have installed MATLink according to the instructions.  I go through these steps.
1. all software off
2. start mathematica
3. run code
            Needs["MATLink`"]
            OpenMATLAB[]
At this stage, everything has happened successfully (no errors), except that I can't see Matlab anywhere on my screen, and it does not appear in my toolbar below either (like it normally would when running).  I can execute all the commands in the tutorial exercises successfully, namely, creating matrices, transposing, checking positively for existence of matlab variables, etc.  Matlab is like a ghost program running in the background somewhere where I can't see it.  

At this point, I double clicked to open a session of matlab manually, which happened without any issues.  But, the same behavior occurs when I repeat the exercises from mathematica.  Nothing shows up in my matlab workspace (it just stays blank), even though things seem to be working correctly on the mathematica side.  

Am I right in thinking that the 'OpenMATLAB[]' command should launch matlab, allowing me to see what is going on on both sides?

Thanks for any help,
Andrew

**Comment by szhorvat** [comment]
This is how it is supposed to work. MATLAB stays in the background and cannot be interacted with.

On Windows only, you can use `CommandWindow["Show"]` to show a MATLAB command window with limited functionality. Evaluate `?CommandWindow` in Mathematica for more information.

Again on Windows only there is a way to connect MATLink to an already running MATLAB session. See here: https://mathematica.stackexchange.com/a/69937/12 We currently consider this method unsupported but last time I checked it still worked.

I hope this helps.
