### ISSUE TITLE
mengine.exe unable to start correctly

### ISSUE THREAD

**Issue by radford7** [rsmenon/MATLink#106]
I just installed MATLink on my computer. I followed the 3 step instructions in the "Link with MATLAB" tab for Windows. Then when i evaluate the command OpenMATLAB[ ], i get an error popup window that says that mengine.exe is unable to start correctly.

I was reading thru the issue opened by hamoodrak 9 days ago and szhorvat said to post the output of the command: MATLink`Developer`GetInfo[]

This is my output below. Any ideas on what the issue might be? This is a really awesome package and would be very useful for my research!

Thank you.

MATLink 1.1 for Windows (Fri 15 Aug 2014)

12.0.0 for Microsoft Windows (64-bit) (April 6, 2019)

Force 32-bit engine: True

System PATH:
C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\Libraries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\Libraries\Windows
C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\12.0
C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\FrontEnd\Binaries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\12.0\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\WINDOWS\System32\NAU_Software
C:\Program Files\PuTTY\
C:\Program Files\MATLAB\R2019b\runtime\win64
C:\Program Files\MATLAB\R2019b\bin
C:\texlive\2019\bin\win32
C:\Program Files (x86)\Wolfram Research\WolframScript\
C:\Program Files\MATLAB\R2019b\bin\win64
C:\Program Files\MATLAB\R2019b\bin\win32
C:\Users\rhm5\AppData\Local\Microsoft\WindowsApps

COM server information:
CLSID: {0818548B-86E8-4451-87C2-AB70D68C490A}
Program ID: Matlab.Application (Version 9.7)
Command: C:\Program Files\MATLAB\R2019b\bin\win64\MATLAB.exe /MLAutomation

**Comment by radford7** [comment]
Nevermind. I was reading thru your Troubleshooting tab and tried the following:

SetOptions[MATLink, "Force32BitEngine" -> False]

That fixed the issue

**Comment by szhorvat** [comment]
Did you set it to `True` previously?

**Comment by radford7** [comment]
Yes i did. I did not read the 3rd step of the Link with MATLAB instructions carefully enough. Thanks for your speedy reply! This is a great piece of software!


Radford Mitchell

Applied Physics and Materials Science

928.523.7375

________________________________
