### ISSUE TITLE
Excuse me, my matlab version is R2020b, and mathrmatica is 13.0， MEvaluate,MGet works to simulate the matlab code in mathematica,. However, the MSet doesn't work  to send mathematica variable to matlab

### ISSUE THREAD

**Issue by Taliw-12** [rsmenon/MATLink#117]
Excuse me, my matlab version is R2020b, and mathrmatica is 13.0， MEvaluate,MGet works to simulate the matlab code in mathematica,. However, the MSet doesn't work  to send mathematica variable to matlab

D:\Programfiles\matlab2020b\bin\win64 is added in system -> path
regmatlabserver  is also done with  administrator rights

**Comment by szhorvat** [comment]
I have not noticed any issues with `MSet` on my computer. "doesn't work" is not a very precise statement. If you get different behaviour than what you expect, please show a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and write the report this this form:

 - This is what I did (_complete_ instructions, starting with "launch Mathematica")
 - This is what I expected to happen
 - This happened instead

Additionally, post the output of ``MATLink`Developer`GetInfo[]``.

**Comment by Taliw-12** [comment]
The output of MATLink`Developer`GetInfo[]:

MATLink 1.1 for Windows (Fri 15 Aug 2014)

13.0.0 for Microsoft Windows (64-bit) (December 3, 2021)

Force 32-bit engine: False

System PATH:
D:\Programfiles\mathematica13\SystemFiles\Libraries\Windows-x86-64
D:\Programfiles\mathematica13
D:\Programfiles\mathematica13\SystemFiles\FrontEnd\Binaries\Windows-x86-64
D:\Programfiles\mathematica13\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
D:\CTEX\UserData\miktex\bin
D:\MikTex\miktex\bin\x64\
D:\CTEX\MiKTeX\miktex\bin
D:\CTEX\CTeX\ctex\bin
D:\CTEX\CTeX\cct\bin
D:\CTEX\CTeX\ty\bin
D:\CTEX\Ghostscript\gs9.05\bin
D:\CTEX\GSview\gsview
D:\CTEX\WinEdt
C:\Windows\SysWOW64
C:\Program Files (x86)\Wolfram Research\WolframScript\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
D:\Programfiles\matlab2020b\runtime\win64
D:\Programfiles\matlab2020b\bin
D:\Programfiles\matlab2020b\polyspace\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
D:\Programfiles\Anaconda
D:\Programfiles\Anaconda\Scripts
D:\Programfiles\Anaconda\Library\bin
D:\Programfiles\Anaconda\Library\mingw-w64\bin
C:\Program Files\Wolfram Research\WolframScript\
D:\Programfiles\matlab2020b\bin\win64
C:\Users\Chuyu\AppData\Local\Programs\Python\Python310\Scripts\
C:\Users\Chuyu\AppData\Local\Programs\Python\Python310\
D:\python\Scripts\
D:\python\
D:\Programfiles\PY\Scripts\
D:\Programfiles\PY\
C:\Users\Chuyu\AppData\Local\Microsoft\WindowsApps

D:\Programfiles\PyCharm Community Edition 2021.2.3\bin

D:\Programfiles\Microsoft VS Code\bin

COM server information:
CLSID: {49C9B3A8-9ADD-4D3E-965F-0850754D5F4B}
Program ID: Matlab.Application (Version 9.9)
Command: D:\Programfiles\matlab2020b\bin\win64\MATLAB.exe /MLAutomation

**Comment by Taliw-12** [comment]
1  The first step, i obtain the mat file computed with matlab.  The command 'MEvaluate' and 'Mget' works in this step
![Snipaste_2022-07-01_21-30-08](https://user-images.githubusercontent.com/58208836/176904345-fd42afff-e7e3-4e9e-8252-e08ed33af2b6.png)
2. Then, with computing, e.g. test2=test1+1, it doesn't display in the work space of matlab

![Snipaste_2022-07-01_21-36-53](https://user-images.githubusercontent.com/58208836/176905477-01797135-f57d-4f0b-a4df-9e77e2c51ce6.png)

**Comment by szhorvat** [comment]
MATLink does not connect to an already running MATLAB. It launches its own private version of MATLAB in the background. Use `MEvaluate["who"]` to see the workspace.

_On Windows only_, there is a way to connect to an already running MATLAB, but I can't consider this supported functionality until we get the time to rewrite MATLink to use more recently introduced APIs. Personally I won't have time for that in the near future. The steps to connect to a running MATLAB are here, but again, consider this unsupported:

https://mathematica.stackexchange.com/a/69937/12

**Comment by Taliw-12** [comment]
Thanks a lot. Matlink is very good. I like it.
