### ISSUE TITLE
MFunction[] should check if MSet[]ing its arguments has was successful

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#12]
`MFunction[]` should check if `MSet`ing its arguments was successful:

What currently happens is that it gives an error about an undefined MATLAB variable.  This is confusing to a user who doesn't know how MFunction works internally.

![Screen Shot 2013-04-02 at 13 36 25 ](https://f.cloud.github.com/assets/1212871/329738/e2757a24-9bbb-11e2-97ac-2f8714487b4b.png)

**Comment by rsmenon** [comment]
This is now fixed.
