### ISSUE TITLE
Mset does not work properly

### ISSUE THREAD

**Issue by pooyaazizi2** [rsmenon/MATLink#120]
Hi
I installed matlink and it work properly but the Mset operator does not work. For example, when I execute the mentioned example in your website:

```
Needs["MATLink`"]
OpenMATLAB[]
MEvaluate["mat = magic(4)"]
mat = MGet["mat"]
MSet["mat_tr", Transpose[mat]]
```
 
The result is:

"
mat =

    16     2     3    13
     5    11    10     8
     9     7     6    12
     4    14    15     1

"

{{16., 2., 3., 13.}, {5., 11., 10., 8.}, {9., 7., 6., 12.}, {4., 14., 
  15., 1.}}

and the Mset no return any result in Matlab and Mathematica.
How can I fix this problem?

**Comment by szhorvat** [comment]
`MSet[]` does not return anything. It merely sets a variable in the MATLAB workspace. You can check that `mat_tr` has been created an set. I just tried that this works as expected. Here's a transcript:

```
In[1]:= << MATLink`

In[2]:= OpenMATLAB[]

In[3]:= MEvaluate["mat = magic(4)"]

Out[3]= ">> 
mat =

    16     2     3    13
     5    11    10     8
     9     7     6    12
     4    14    15     1

"

In[4]:= mat = MGet["mat"]

Out[4]= {{16., 2., 3., 13.}, {5., 11., 10., 8.}, {9., 7., 6., 
  12.}, {4., 14., 15., 1.}}

In[5]:= MSet["mat_tr", Transpose[mat]]

In[6]:= MEvaluate["mat_tr"]

Out[6]= ">> 
mat_tr =

    16     5     9     4
     2    11     7    14
     3    10     6    15
    13     8    12     1

"

In[7]:= MGet["mat_tr"]

Out[7]= {{16., 5., 9., 4.}, {2., 11., 7., 14.}, {3., 10., 6., 
  15.}, {13., 8., 12., 1.}}
```

**Comment by pooyaazizi2** [comment]
Dear Szabolcs
Thank you very much for your answer.
I am very glad that a person answer to my question because this issue is a
big problem for me.
Although, I do not find my answer because I think with Mset , we should be
able to transfer expressions to Matlab workspace to continue the work with
Matlab, but when I use Mset no variable is created in Matlab workspace or
Matlab's command window and even when I type mat_tr in Matlab, the
following message is displayed:
Undefined function or variable 'mat_tr'.

with the best regards


On Mon, Feb 6, 2023 at 1:28 AM Szabolcs Horvát ***@***.***>
wrote:
>
> MSet[] does not return anything. It merely sets a variable in the MATLAB
workspace. You can check that mat_tr has been created an set. I just tried
that this works as expected. Here's a transcript:

**Comment by szhorvat** [comment]
The transcript I included above demonstrates that `mat_tr` is indeed set. I can use `MEvaluate["mat_tr"]` or `MGet["mat_tr"]` to get its value. Does this not work for you?

However, it sounds like you have started a MATLAB session manually, and you were expecting Mathematica to communicate with it. Perhaps you were trying to access `mat_tr` in a separate MATLAB window?

That's not quite how MATLink works. It starts its own _private_ MATLAB session. Any MATLAB you started manually will be independent of it. This limitation is imposed by the API that MATLAB provided at the time when MATLink was written. Recent versions of MATLAB have a much more flexible API that would allow connecting to an already running MATLAB instance, but unfortunately I do not have the time to rewrite MATLink to make use of this new API.

If you are on Windows, you _can_ actually connect to an existing session, but that requires a bit of manual setup. I explain how to do this here: https://mathematica.stackexchange.com/a/69937/12 Note that this is only possible on Windows, not on Linux or macOS.

**Comment by pooyaazizi2** [comment]
Thank you very much sir for your replies.
You are right. I was opening Matlab manually.
After you said, I closed matlab and ran the example code(that is in matlink
site) in mathematica, the matlink is running but Matlab is opened for short
seconds and automatically is closed. the picture of Matlab command windows
opened is below:

[image: image.png]

I think the connection between two software is not created correctly
because, in some times, the following error is displayed in mathematica
when I run example code:

Not connected to the MATLAB engine
or
MATLink has lost connection to the MATLAB engine; please restart \
MATLink to create a new connection. If this was a crash, then please \
try to reproduce it and open a new issue, making sure to provide all \
the details necessary to reproduce it.
[image: image.png]

The method for connecting to  the currently running instance of MATLAB
<http://www.mathworks.com/help/matlab/ref/enableservice.html>, is not
successful in my computer and no variable is displayed in matlab workspace.

although, in all aboved cases, the results of MEvaluate(mat_tr) and
Mget(mat) in Mathematica are true (please see the following picture.
[image: image.png]

What should I do?

With the best regards
