### ISSUE TITLE
engEvalString() hangs on incomplete input

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#2]
The MATLAB engine function `engEvalString()` and it's mEngine equivalent `engCmd[]` _hang_ when given incomplete MATLAB commands such as `"x=[1 2"` or `"for i=1:10"`.

We need to implement a wrapper which calls eval or evalc in MATLAB, detects if the input is incomplete or has a syntax error, and reports accordingly.

**Comment by rsmenon** [comment]
Mathworks acknowledged this as a limitation of `engEvalString()` in a response to Sz's support request. I've implemented a workaround for this using MATLAB's `checkcode()` function which parses and detects errors in the code. If errors are found, the code is not evaluated and the error message is displayed. If `checkcode()` doesn't return any errors, the code is evaluated.

![](https://f.cloud.github.com/assets/2389211/134434/7ca6cc42-70d8-11e2-9fc2-9517f7a8e0f0.png)
