### ISSUE TITLE
Create a test-suite

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#21]
It would be very useful to have a test suite that tests both basic functionality and edge cases.

Ideally there would be one test quite for the eng\* functions and one for the M\* functions, but since we're short on time, let's do the M\* ones only for now.

This is important to ensure that unsafe changes (especially to the C++ code) do not break anything, or ensuring that porting to a new platform (e.g. 32 bit) has worked.

**Comment by rsmenon** [comment]
I have a few unit tests written to test the M\* functions (I run them after each compile/change to the package to see if something has broken).  I'll clean them up a bit and push them later... should provide a starting point.

**Comment by szhorvat** [comment]
What else is needed here?
- We could go through the closed bugs and make sure that a test is present for most of them (in case the same breakage would appear again).
- I've a few more edge cases to add for data structure translation.
- I didn't explicitly test MFunction & MScript (though some tests rely on them)
- Messages and error checking (probably less important)
- Make sure that things will work after a CloseMATLAB[];OpenMATLAB[], after a MATLAB crash (check in the crash MEX file), or after an engine crash (`killall mengine`).  Could you do this part Ravi? You already have some tests in this area.
