### ISSUE TITLE
Make MSet[] report the cause of failure whenever possible

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#27]
MSet[] should report the cause of failure whenever possible to make it easier to find why it failed with a complex object (e.g. a struct).  If should report the offending sub-element in the error message.

If should indicate if the error is coming from the MATLAB Engine instead of the Mathematica layer.

**Comment by rsmenon** [comment]
This is now fixed (I'll tweak the error message a bit more later)

![](https://f.cloud.github.com/assets/2389211/371135/6467ff6e-a31b-11e2-97e5-1abb67a1c8f7.png)
