### ISSUE TITLE
If MATLAB crashes because of an MEvaluate, it triggers StringFreeQ::strse in MATLink

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#32]
If MATLAB crashes because of an MEvaluate, it triggers StringFreeQ::strse in MATLink

I don't consider this a MATLink bug because MATLAB just shouldn't crash (reported to MW), but it's something worth documenting.

The following input crashes MATLAB R2013a on OS X (but it leaves mengine running)

```
obj = DelaunayTri(rand(10,2))
struct(obj)
```

We can use this to test how MATLink would cope with a crashing MATLAB.

**Comment by rsmenon** [comment]
Regardless of whether MATLAB crashes or not, the errors were annoying. These are now caught and handled. All MATLAB crashes in MEvaluate are handled the same way. I'll investigate and fix crash handling in other M\* functions as I come across them.

![](https://f.cloud.github.com/assets/2389211/377381/46f57bde-a4a4-11e2-8c55-164de757193a.png)
