### ISSUE TITLE
Creating an MScript and overwriting it right away fails sometimes

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#41]
Creating an MScript and overwriting it right away fails sometimes.  Unfortunately this is not consistently reproducible, and seems to be timing related.  Paste the code in a notebook and use Evaluation -> Evaluate notebook to reproduce the issue.

![Screen Shot 2013-04-16 at 15 35 11 ](https://f.cloud.github.com/assets/1212871/387898/cb23b7c0-a6cc-11e2-8b64-af6f50e4334e.png)

Note that the output should be `Goodbye!`.

Here's the plain text code:

```
<< MATLink`

OpenMATLAB[]

(*create a script*)
hello = MScript["hello", "disp('Hello world!')"];
MEvaluate[hello]

(*overwrite and test again*)
hello = 
 MScript["hello", "disp('Goodbye!')", "Overwrite" -> True]
MEvaluate[hello]
```

**Comment by rsmenon** [comment]
Hmm... Looks like some race condition due to mma's "Evaluate Notebook". I don't know yet why it happens, but inserting a small pause doesn't cause the problem. Looking into this now...

**Comment by szhorvat** [comment]
Race conditions happen in multithreaded programs:  the behaviour may be
different if thread 1 accesses the data first or if thread 2 accesses the
data first.  This might depend on timing (so thread 1 and thread 2 are
'racing' to the data).  We don't have any multithreaded thing here.  Also,
it's not "Evaluate Notebook"'s fault alone because it always happens i the
workbench (which doesn't use the front end).

**Comment by rsmenon** [comment]
So far, we know that this is a MATLAB issue, not Mathematica (or perhaps both/OS?) and quite possibly related to how it handles I/O . I don't know enough to say if this is a bug or not, but this is a minimal MATLAB example to reproduce:

``` matlab
% save this file as write2file.m
function write2file(fname, str)
    fid = fopen(fname,'w');
    fprintf(fid, str);
    fclose(fid);
end
```

followed by 

``` matlab
% run this file as a script
write2file('tmp.m','disp(''hello!'')')
tmp

write2file('tmp.m','disp(''goodbye!'')')
tmp
```

**Comment by szhorvat** [comment]
I think the solution described [here](http://www.mathworks.com/support/solutions/en/data/1-1PFIYH/index.html?product=ML&solution=1-1PFIYH) will be good.  We simply need to `clear` the script after overwriting it.  What do you think?  Would there be issues if something with the same name as the script already exists?
