### ISSUE TITLE
Failed to install on Linux 64 bit

### ISSUE THREAD

**Issue by bgatessucks** [rsmenon/MATLink#49]
Needs["MATLink`"] gives no problems, however OpenMATLAB[] fails with the following error message :
OpenMATLAB::noopen: Could not open a connection to MATLAB. >>

This is what I get in my console when starting Mathematica 
$ mathematica > /tmp/firstrun.txt
set.cpp: In function ‘void eng_make_String(const short unsigned int*, int, int)’:
set.cpp:159:31: warning: narrowing conversion of ‘len’ from ‘int’ to ‘mwSize {aka long unsigned int}’ inside { } is ill-formed in C++11 [-Wnarrowing]
set.cpp: In function ‘void eng_make_Struct()’:
set.cpp:191:5: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

---Start firstrun.txt
/opt/Wolfram/Mathematica/9.0.1/Executables/../SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions/mprep -prototypes mengine.tm > menginetm.cpp
g++ -O -Wall -I/opt/Wolfram/Mathematica/9.0.1/Executables/../SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions -I/opt/matlab/R2013a/bin/../extern/include -L/opt/Wolfram/Mathematica/9.0.1/Executables/../SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions -L/opt/matlab/R2013a/bin/../bin/glnxa64 menginetm.cpp mengine.cpp set.cpp get.cpp main.cpp -Wl,-rpath-link,/opt/matlab/R2013a/bin/../bin/glnxa64/ -lML64i3 -lmx -leng -o mengine
---End firstrun.txt

**Comment by szhorvat** [comment]
If you open a terminal and go to `MATLink/Engine/bin/Unix64`, then start `./mengine.sh`, does it give you the `Create link:` prompt?

Which Linux distro are you using and what is your gcc version?  Could you please send an email to matlink.m@gmail.com, so we can continue in email?

**Comment by bgatessucks** [comment]
yes

**Comment by szhorvat** [comment]
Which Linux distro are you using and what is your gcc version? Could you please send an email to matlink.m@gmail.com, so we can continue in email?

**Comment by szhorvat** [comment]
In order to connect to MATLAB, it's necessary to have `csh` installed at `/usr/bin/csh` (as described in the Link with MATLAB section of the docs).  This is a requirement for all programs using the MATLAB Engine C API.
