### ISSUE TITLE
Add error checking to option values (e.g. in MFunction)

### ISSUE THREAD

**Issue by szhorvat** [rsmenon/MATLink#5]
Add error checking to option values.

I accidentally used MFunction["eig", "Output" -> 2] instead of MFunction["eig", "OutptutArguments" -> 2].  There was no indication that this was incorrect.

**Comment by rsmenon** [comment]
This is now fixed. You will get messages if you use incorrect options (e.g. "Outputs")  or invalid option values (e.g. "Output" -> "Yes")
