### ISSUE TITLE
MATLink Engine not compiling

### ISSUE THREAD

**Issue by ghost** [rsmenon/MATLink#52]
I've followed the installation instructions, but when I run OpenMATLAB[] I get the error:

MATLink`Developer`CompileMEngine::failed: Automatically compiling the MATLink Engine has failed. Please try to compile it manually and ensure that the path to the MATLAB directory is set correctly in the makefile.

Huh?

I am running Ubuntu 12.10 with Mathematica 8.04 and Matlab R2013a.

**Comment by szhorvat** [comment]
Can you send an email to matlink.m@gmail.com ?  Then we can try to debug this.  Are you running a 32-bit or 64-bit Linux?  What about Mathematica and MATLAB? Are they 32-bit or 64-bit versions?  Do you have a student version of MATLAB?

**Comment by szhorvat** [comment]
Please also try to run Mathematica in command line mode (type `math` at the terminal), then do

```
Needs["MATLink`"]
MATLink`Developer`CompileMEngine[]
```

Let me know what output you see in the terminal.  It should contain the relevant error message.

**Comment by rsmenon** [comment]
Per email correspondence, user did not have permission to execute `mengine.sh`. Running `sudo chmod +x mengine.sh` solved the problem. This should normally not happen, as the repo and the zip download both have files with the right permissions.

**Comment by rsmenon** [comment]
Upon further inspection, it looks like the `ProjectInstaller` option doesn't preserve file permissions (I hadn't noticed this before). I've emailed the developer and opened an issue: lshifr/ProjectInstaller#1
