### ISSUE TITLE
Error involving libmx.dll

### ISSUE THREAD

**Issue by picardo21** [rsmenon/MATLink#56]
Although I have followed the instruction for Windows OS and included (bin/win64) in the PATH, I still receive the error of :
"the program cant start because libmx.dll is missing form your computer"
when I execute OpenMATLAB[]

I am attempting to use MATLink with Matlab 2011a and Mathematica 8.0 (both 64-bit) on Windows 7

**Comment by szhorvat** [comment]
This error indicates that the folder you added to the path does not contain libmx.dll.  Please check the location of libmx.dll and add the correct folder to the path.  If you're still having trouble after, send an email to matlink.m@gmail.com and let's continue the debugging there.  Also send me the output of `Environment["PATH"]` when evaluated in Mathematica, so we can check that the correct folder is indeed in the path and Mathematica does see it.

**Comment by szhorvat** [comment]
Turns out the folder was not added to the path after all.  Solved.

**Comment by ghost** [comment]
I have the same problem but libmx.dll is on the matlab path. Any ideas?
