### ISSUE TITLE
Cannot run OpenMATLAB[] in Windows

### ISSUE THREAD

**Issue by Vidri** [rsmenon/MATLink#57]
Having added MATLAB\bin\win64 to the system PATH, I get this error when trying to run OpenMATLAB[].

```
MATLink`Developer`CompileMEngine::unsupp:
Automatically compiling the MATLink Engine from source for Windows is not supported. Please compile it manually.
```

I could not find this error on the MATLink website.

**Comment by szhorvat** [comment]
On Windows this error will come up if MATLink can't find it's executable, `mengine.exe`.  It is likely that MATLink is not installed correcty on your system.  Please check that the MATLink directory was moved to the correct place (`%appdata%\Mathematica\Applications` on Windows) and make sure that the subdirectory `MATLink\Engine\bin\Windows64` contains `mengine.exe`.

**Comment by Vidri** [comment]
Uf, thanks a lot for answering. I think I misplaced the directory when I used my local admin account to edit the system path. It works now.
Mihai

**Comment by GuyPardo** [comment]
I have the same problem. Mathematica 12, windows 10. 
The MATLink directory is located at %appdata%\Mathematica\Applications, and I've checked that MATLink\Engine\bin\Windows64 contains mengine.exe exists.
I still get the error:

MATLink`Developer`CompileMEngine::unsupp: Automatically compiling the MATLink Engine from source for Windows is not supported. Please compile it manually.

**Comment by szhorvat** [comment]
@GuyPardo:

 1. Where did you obtain MATLink?
 2. What does ``FindFile["MATLink`"]`` return?

**Comment by GuyPardo** [comment]
@szhorvat 

1. from here:
http://matlink.org/

2. "C:\\Users\\Owner\\AppData\\Roaming\\Mathematica\\Applications\\\
MATLink.wl"

**Comment by szhorvat** [comment]
>     2\. "C:\Users\Owner\AppData\Roaming\Mathematica\Applications\
>         MATLink.wl"

This file is not part of the official MATLink package.  Why did you create it?

**Comment by GuyPardo** [comment]
not sure.. maybe it's because I previously tried to install the package from the Mathematica "install" menu.
anyway, deleting the file solved the problem, so thanks a lot
