### ISSUE TITLE
MEvaluate[] not finding files from specified directory

### ISSUE THREAD

**Issue by RichardAfolabi** [rsmenon/MATLink#60]
```
MEvaluate["pwd"] 
```

shows current working directory as "C:\Users\PCname\Documents". Any file I place here can be found directly and evaluated. However, for the sake of organization, my files cannot all be dumped in this directory. If I specify

```
MEvaluate["C:\\Users\\PCname\\Documents\\Matlab\\projectxyz\\fyfile"]
```

It bursts out "Unexpected MATLAB operator" errors. How can I solve this? 

Thanks

**Comment by szhorvat** [comment]
The string passed to `MEvaluate` must contain correct MATLAB input.  `C:\Users\PCname\Documents\Matlab\projectxyz\fyfile` is not syntactically correct MATLAB input and wouldn't work if you type it directly in the MATLAB command line either.

However, you set the working directory to that one:  `MEvaluate["cd C:\\Users\\PCname\\Documents\\Matlab\\projectxyz"]`

Alternatively you can use MATLAB's `run` command to run the file, or use `addpath` to add that directory to the MATLAB path.  You can look up these commands in the MATLAB documentation.

**Comment by RichardAfolabi** [comment]
Oh my! silly newbie me.
I was thinking mathematica command inside the MEvaluate[]
Thanks for the help. It works.
