### ISSUE TITLE
MATLink producing error on some MATLAB routines

### ISSUE THREAD

**Issue by RichardAfolabi** [rsmenon/MATLink#61]
I currently run MATLAB with [**GAMS optimization solvers**](http://www.gams.com/docs/intro.htm) which has been working pretty well. Now I need to use MATLAB from Mathematica, hence the need for MATLink.

GAMS has 2 special MATLAB routines `rgdx('outputfile',struct1,struct2)` and `wgdx('inputfile',struct1,struct2)` that help us to [**transfer data from MATLAB to GAMS**](http://gams.com/dd/docs/tools/gdxmrw.pdf).

However, when I use MATLink to run MATLAB from mathematica with any of those two routines, I get an error: 

```
MATLink::errx: Error using ==> wgdx
Incorrect type of input argument. Structure expected.

Error in ==> input at 1 
wgdx('inputfile',struct1,struct2)
```

It appears MATLink is having a problem with the routine which interestingly works fine when executed in MATLAB. I've tried using `MATLABCell[]` and `CommandWindow["Show"]` but both also give errors.

Any suggestions for me?

**Comment by szhorvat** [comment]
Can you please give a complete minimal example?

What I mean by that, can you provide the precise command you type into Mathematica, and its output (both the errors and the output).

Also, can you provide the equivalent command that you use in MATLAB and works?

**Comment by RichardAfolabi** [comment]
First, I set both MATLAB and Mathematica to the same working directory:

```
 SetDirectory["C:\\Users\\PC\\Dropbox\\MATLAB-GAMS"]
 MEvaluate["addpath C:\\Users\\PC\\Dropbox\\MATLAB-GAMS; savepath;"]
```

Interfacing MATLAB-GAMS, we use:

```
wgdx('inputfile.gdx',struct1,struct2)        #to transfer input data or     
rgdx('outputfile.gdx',struct1,struct2)       #to read output data to MATLAB workspace
```

where both `struct1` and `struct2` are MATLAB structure implemented with:

```
MSet["struct1", MEvaluate["struct('name','grd','type','set','val',linspace(1,5,10))"]]
MSet["struct2", MEvaluate["struct('name','Nitems','type','set','val',randi([2,10],1,10))"]]
```

So to read the data into GAMS through MATLAB and MATLink, I typed the Mathematica code:

```
MEvaluate["wgdx('inputfile.gdx',struct1,struct2)"]
```

I got the output:

```
$Failed
```

On the `Message window` I receive the error:

```
MATLink::errx: Error using ==> wgdx
Incorrect type of input argument. Structure expected.

Error in ==> input at 1 
wgdx('inputfile.gdx',struct1,struct2)
```

Same message and error occur when I use the `rgdx` as well. Please let me know if you need more information

**Comment by rsmenon** [comment]
@RichardAfolabi You are using MATLink's commands incorrectly. `MSet` is used to transfer a data object from _Mathematica_ to MATLAB. `MEvaluate` is used to run commands in MATLAB. The output of `MEvaluate` is a string, which is the same as what is displayed in the command window. To see what I mean, try evaluating 

```
MEvaluate["struct('name','grd','type','set','val',linspace(1,5,10))"]
```

in your notebook. You should see something like 

```
>> 
ans = 

    name: 'grd'
    type: 'set'
     val: [1 1.4444 1.8889 2.3333 2.7778 3.2222 3.6667 4.1111 4.5556 5]
```

which is a string, not a struct. Now you're setting this string to `struct1` which is then passed to your GAMS program, which then gives an error (rightfully). 

Instead, what you want to be doing is to pass a list of rules to `MSet`, which is then converted to a struct in MATLAB. Example:

```
MSet["struct1", {"name" -> "grd", "type" -> "set",  "val" -> Array[# &, 10, {1, 5}]}]
```

You can now check that `struct1` in MATLAB is indeed a struct.

Please go through our [documentation](http://matlink.org/documentation/) on the different commands and what they do.

**Comment by RichardAfolabi** [comment]
Thanks so much for your kind response and for giving us an amazing tool!
