### ISSUE TITLE
OpenMATLAB[] fails on Win7 64bit with server-licenced MATLAB

### ISSUE THREAD

**Issue by horoman** [rsmenon/MATLink#63]
I followed the instructions on http://matlink.org/#installation for Windows
First I am new to mathematica and packages. Out of the instructions I had no clue where to extract the zip. Found the right place after an hour.
Second it was not clear to me what the system PATH is. I finally found it but I think the explanation could be better (I assume that people who don't know the system well, will not find this).
regmatlabserver fails (started MATLAB R2013a 64bit as Administrator), error:

> Error using regmatlabserver (line 42)
> While executing ["C:\Program Files\MATLAB\R2013a\bin\matlab" /wait /regserver /r quit], the following error was
> reported by DOS with status 9:

(there is no more text after the ":"). I need a VPN connection to my University to run MATLAB, it somehow needs a licence from there. Maybe that's not common and causing this error.
Needs["MATLink`"] in Mathematica seems to work.
OpenMATLAB[] returns

> OpenMATLAB::noopen: Could not open a connection to MATLAB.

Furthermore a window with the "title mengine(uh3_shm)" opens.

Two things now:
1. Could you help me to make MATLink run (is there a support page?)
2. Please clearify your installation instructions for Windows in a way it is clear for non-expert users, too.

Thanks for your work!
Roman

**Comment by szhorvat** [comment]
Can you send an email to matlink.m at gmail so we can continue this discussion there?

**Comment by szhorvat** [comment]
In the meantime, one possible reason why `regmatlabserver` has failed may be that MATLAB wasn't run as administrator.  Please try this: 
1. close all running instances of MATLAB.
2. right click the MATLAB icon and choose "Run as administrator"
3. try `regmatlabserver` again and see if it still gives errors

Let me know (in email) how it went.
