### ISSUE TITLE
Failure to compile MATLink automatically

### ISSUE THREAD

**Issue by shakasaki** [rsmenon/MATLink#64]
Hello,

I am trying to get started with MATLink using Mathematica 9.0, MATLAB 2013b and Ubuntu 12.04 LTS. I Followed the instructions and i made sure to have csh and gcc up to date. Running which matlab and which math in a terminal gives me 
% which matlab
/usr/local/bin/matlab
% which math
/usr/local/bin/math

I copied the files in the directory that opens when running the Mathematica command SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}](copied the entire MATLink folder) but when I try to use MATLink I get the following error:

MATLink`Developer`CompileMEngine::failed: Automatically compiling the MATLink Engine has failed. Please try to compile it manually and ensure that the path to the MATLAB directory is set correctly in the makefile.

Thank you in advance for the help!

**Comment by szhorvat** [comment]
Do you have a 32-bit or 64-bit version of Ubuntu, Mma and MATLAB?  Can you reply to matlink.m at gmail.com please, then we'll try to figure out why it's not working.

**Comment by shakasaki** [comment]
Thanks for the quick response! I replied to the mentioned email address

**Comment by rsmenon** [comment]
From email correspondence, user did not have `g++` installed (is not installed by default on Ubuntu). Installing `g++` and recompiling fixed the problem. This is now noted at http://matlink.org/troubleshooting/
