### ISSUE TITLE
OpenMATLAB[] fails with CompileMEngine::unsupp error

### ISSUE THREAD

**Issue by ebauch** [rsmenon/MATLink#65]
I followed all instructions on the Matlink page, but I can't make it work. It always fails with the following error:

![icon](https://cloud.githubusercontent.com/assets/3758223/2871204/bd6cb180-d2fa-11e3-8dd4-56637e2b60ab.png)

Here are my specs: 

Win 7 64 bit
Matlab 2013a
Mathematica 9.0.1 64 bit (student ed)

Thanks for helping resolving this!

**Comment by szhorvat** [comment]
This error should never appear on Windows if MATLink is installed correctly and all files are intact.  It indicates that MATLink cannot find `mengine.exe`, which comes bundled with the package.  If you see this error on Windows, it means that your MATLink installation is broken.

Please re-install MATLink completely: delete the `MATLink` directory, re-download MATLink, extract the zip files, then place the MATLink directory in the folder opened by `SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}]`.

If you have a student version of MATLAB R2013a, then it is 32-bit, so start MATLink like this:

```
Needs["MATLink`"]
SetOptions[MATLink, "Force32BitEngine" -> True]

OpenMATLAB[]
```

**Comment by ebauch** [comment]
Hi Szhorvat, 

thank you for your help, I'd really like to make this work. I did what you said and now I am getting an error that mengine cannot be run:

With 32 Bit Option enabled I get 

![selection_019](https://cloud.githubusercontent.com/assets/3758223/2874181/cdebbfc0-d3da-11e3-8d04-d0f168e4da0c.png)

Without 32 Bit Option enabled I get the following error

![selection_018](https://cloud.githubusercontent.com/assets/3758223/2874174/8eb6c872-d3da-11e3-840d-3bf85e795de2.png)

I checked more carefully, Matlab should be 64 bit since it is installed in the program files folder, not x86 program files. It also contains a bin/win64 directory. 

Mathematica is 64 bit too 

![selection_016](https://cloud.githubusercontent.com/assets/3758223/2874165/2e3fb526-d3da-11e3-85d6-b350bb7f8937.png)

Seems like there is something fishy. 

Thanks for help, 

Erik

**Comment by ebauch** [comment]
Based on some searching also on the error messages above, it looks like that the wrong DLLs are used when calling mengine. I opened the mengine.exe with [Dependecy Walker](http://www.dependencywalker.com/) and this is how it looks: 

![selection_004](https://cloud.githubusercontent.com/assets/3758223/2874647/6eaea77e-d3f4-11e3-9b54-39d2ddd967bb.png)

I noticed that I had an older 32bit Matlab version installed, along the 2013a 64 bit. I uninstalled it, but it didn't do the trick.

**Comment by szhorvat** [comment]
I was away today and now it's late.  Let us continue this in email which is a more suitable medium for this type of troubleshooting.  Please send a mail to matlink.m at gmail.com and I'll reply tomorrow.

Until then:

If you have a _student version_ of 2013a, it's 32-bit, not 64-bit.  If it's 64-bit it's not a student version.  Only 2014a is available in 64-bit student version for Windows.

For MATLink to work, you need to add MATLAB's bin/win32 (bin/win64 for 64-bit versions) directory to the PATH.  It is important that this should be done _only_ for a single version of MATLAB if multiple versions are installed.

You need to run MATLAB as administrator and execute `regmatlabserver`.  This needs to be done once only, and for the version of MATLAB that you're going to use wit MATLink.

We'll continue in email tomorrow.

**Comment by szhorvat** [comment]
An incompatible version of `tbb.dll` was in the `Windows\System32` folder which prevented `mengine.exe` from using the `tbb.dll` that ships with MATLAB.  Removing this DLL fixed the problem.
