### ISSUE TITLE
MATLink doesn't work

### ISSUE THREAD

**Issue by odobo3581** [rsmenon/MATLink#78]
this code, 

Needs["MATLink`"]
OpenMATLAB[]

returns,

The program can't start because ml64i4.dll is missing from your computer. Try reinstalling the program to fix this problem

**Comment by szhorvat** [comment]
Please send an email to matlink.m at gmail about this.

**Comment by szhorvat** [comment]
What is the version of Mathematica you are using?

As a temporary measure, you can download the missing DLL from [here](https://dl.dropboxusercontent.com/u/38623/MathLinkDLL.zip).

In Mathematica, evaluate

```
SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications", "MATLink", "Engine", "bin", "Windows64"}]
```

to locate the 64-bit version of `mengine.exe`.  Drop the DLL next to this executable.  Restart Mathematica and try again.

**Comment by odobo3581** [comment]
version 9.0.1 
windows 64 bit

**Comment by rsmenon** [comment]
@odobo3581 So did it work?

**Comment by odobo3581** [comment]
Yes, it worked. Thank you.  And I emailed matlink.m

**Comment by szhorvat** [comment]
Duplicate of #76
