### ISSUE TITLE
OpenMATLAB[] hangs (Windows7, Matlab2014a, Mathematica10)

### ISSUE THREAD

**Issue by mineraldragon** [rsmenon/MATLink#79]
- MATLAB's bin\win64 directory is in the system PATH
- ran regmatlabserver in Matlab running as administrator
- contents of MATlink zip file are in directory opened by SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}]
  -Needs["MATLink`"] executes fine

I don't get an error message. Mathematica says 'running...', but won't respond to anything else. I presume a Matlab window should be opening and 'running...' should end. 
Any ideas would be welcome,
R

**Comment by szhorvat** [comment]
MATLink doesn't work with MATLAB R2014a on Windows due to a MATLAB bug.  Earlier and later versions of MATLAB are fine.

Please upgrade to MATLAB R2014b.
