### ISSUE TITLE
Problem Matlab 2015a and Mathematica 10

### ISSUE THREAD

**Issue by assan3** [rsmenon/MATLink#81]
Good morning,

I have a problem with MATLink using Mathematica 10 and Matlab 2015a. 
When I load the package from mathematica and try to type the command: "OpenMATLAB[]", matlab is launched (and opened),  but after a long time the command is still running on mathematica, so it's impossible to type any other commands on the mathematica workspace.
What can I do to solve this issue?

**Comment by szhorvat** [comment]
Please send an email to matlink.m at gmail, and include:
1. complete version information for your OS, Mathematica and MATLAB
2. restart Mathematica, then evaluate:

```
Needs["MATLink`"]
MATLink`Developer`GetInfo[]
```

and include the output
1. if you run Windows, check if there are any error dialogs hidden behind open windows.  If yes, include a screenshot
2. do you have LabView installed?

We can continue in email.  I'm closing this issue now as the issue tracker is not really suitable for support.
