### ISSUE TITLE
How to install MathLink

### ISSUE THREAD

**Issue by Juddd** [rsmenon/MATLink#84]
I'm sorry to failure to understand your "Download and install MATLink to a location in Mathematica's $Path" in you directory,Yeah,I can download your MATLink.zip.But how to install it?When I try to execute the MATLink\Engine\bin\Windows64 to install it,a pop window prompt that my computer is lose libmx.dll and libeng.lib,And I can't run "Needs["MATLink`"];OpenMATLAB[]".So help me please.

**Comment by Juddd** [comment]
I have checked the MatLab is added in my path like this:

C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;E:\processing-3.0b6\;C:\Users\zyd199012\AppData\Local\Programs\Python\Python35\;C:\Program Files\MATLAB\R2015b\runtime\win64;C:\Program Files\MATLAB\R2015b\bin;C:\Program Files\MATLAB\R2015b\polyspace\bin

**Comment by rsmenon** [comment]
@Juddd The instructions are right after the sentence you quoted in http://matlink.org/#installation:

> Download the zip file and extract the contents to the folder opened by 
> 
> ```
> SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}]
> ```

Please execute the above command in _Mathematica_. It will give you the directory to which you will have to extract the contents of the zip file. 

For rest of the instructions for Windows, please see the "Link with MATLAB > Windows" section under http://matlink.org/#installation. If you run into any issues, please also check http://matlink.org/troubleshooting/ to see if it has already been addressed.

If you still have issues, please send us an email at matlink.m@gmail.com with all the details (Operating system, MATLAB and _Mathematica_ versions, contents of your Windows path, _Mathematica_'s `$Path`, etc.).
