### ISSUE TITLE
No libmx.dll with Matlab R2015a?

### ISSUE THREAD

**Issue by jpat34721** [rsmenon/MATLink#86]
I can't find a libmx.dll file except for the 32-bit version. There is no bin64 directory in my installation. Is MATLink not compatible with R2015a?

**Comment by szhorvat** [comment]
Please check the troubleshooting page and try the solution there first: http://matlink.org/troubleshooting/
If it does not work, you will need to provide the output of the command `MATLink`Developer`GetInfo[]`, as described at the top of the troubleshooting page, as well as complete information about your system (OS version, Mathematica & MATLAB versions, etc.)
