### ISSUE TITLE
Unable to link MATLAB with Mathematica

### ISSUE THREAD

**Issue by Sugajen** [rsmenon/MATLink#89]
After registering the default MATLAB version when I run this
**Needs["MATLink`"]
SetOptions[MATLink, "Force32BitEngine" -> True]**
I get two errors saying _" The program can't start because libmx.dll is missing from your computer. Try installing the program to fix this problem. "
_and_ 
" The program can't start because libeng.dll is missing from your computer. Try installing the program to fix this problem. "_
Any help is greatly appreciated.

**Comment by rsmenon** [comment]
Please see the instructions for this issue on our [troubleshooting](http://matlink.org/troubleshooting/) page.

**Comment by Sugajen** [comment]
Thank you! that solved previous issue. But now it says unable to start correctly, though the  "SetOptions[MATLink, "Force32BitEngine" -> True]" is used.

**Comment by rsmenon** [comment]
What version of _Mathematica_ and MATLAB are you running? Please post the output of ``MATLink`Developer`GetInfo[]``.

**Comment by Sugajen** [comment]
Mathematica 11.0 Student Edition and MATLAB 2016b. 
The output is
MATLink 1.1 for Windows (Fri 15 Aug 2014)

11.0.1 for Microsoft Windows (64-bit) (September 20, 2016)

Force 32-bit engine: True

System PATH:
C:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Libraries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Libraries\Windows
C:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\11.0
C:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\FrontEnd\Binaries\Windows-x86-64
C:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\MATLAB\R2016b\bin
C:\Users\Sugajen\AppData\Local\Microsoft\WindowsApps
C:\Program Files\MATLAB\R2016b\bin\win64


COM server information:
CLSID: {6A239BA0-2DE5-4D03-8B4D-3790D50AC64F}
Program ID: Matlab.Application (Version 9.1)
Command: C:\Program Files\MATLAB\R2016b\bin\win64\MATLAB.exe /MLAutomation

**Comment by rsmenon** [comment]
You have a 64 bit MATLAB so you shouldn't set `"Force32BitEngine" -> True`. This option is only for legacy MATLAB versions that have are 32 bit. 

Please run ``MATLink`Developer`ResetSettings[]`` and restart MATLink.

**Comment by Sugajen** [comment]
Works perfectly! Thank you for your prompt responses.
