### ISSUE TITLE
How to install MATlink?

### ISSUE THREAD

**Issue by xuanxieliu** [rsmenon/MATLink#91]
After download the zip file from matlink.org and extract the contentes to the folder opened by
   /   SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}] /  ,
 I execute the following in a mathematica notebook:  
   /  Needs["MATLink`"] /
    /OpenMATLAB[]   /   
But I failed. A small window appeared writing " libmx.dll is missing"

**Comment by szhorvat** [comment]
Please check the troubleshooting section of the website, which discusses precisely this problem (as well as several others):

http://matlink.org/troubleshooting/
