### ISSUE TITLE
Problem when  insatll MATLink

### ISSUE THREAD

**Issue by xuanxieliu** [rsmenon/MATLink#92]
I try to follow the steps listed on matlink.org, 
 1. add MATLAB's  bin\win64 directory to the  operating system's path environment variable; 
 2. Run / regmatlabserver / in MATLAB; 
  3.  /  Needs["MATLink`"]  /
4./OpenMATLAB[] /
Then I was warned by " the program can't start because libmx.dll is missing from your computer".
I already check the troubleshooting section of matlink.org. But I didn't found feasible approach.
I also viewed other issues about this problem, but also do not help.
Any help is appreciated, I hope for your help.

**Comment by szhorvat** [comment]
As noted at the top of the troubleshooting page, we need detailed information about your system, including the output of ``MATLink`Developer`GetInfo[]`` before we can help.

**Comment by xuanxieliu** [comment]
MATLink 1.1 for Windows (Fri 15 Aug 2014)

10.2.0 for Microsoft Windows (64-bit) (July 7, 2015)

Force 32-bit engine: False

System PATH:
E:\Wolfram.Mathematica\SystemFiles\Libraries\Windows-x86-64
E:\Wolfram.Mathematica\SystemFiles\Libraries\Windows
E:\Wolfram.Mathematica\SystemFiles\Kernel\Binaries\Windows-x86-64
E:\Wolfram.Mathematica
E:\Wolfram.Mathematica\SystemFiles\FrontEnd\Binaries\Windows-x86-64
E:\Wolfram.Mathematica\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin
C:\ProgramData\Lenovo\ReadyApps
E:\LaTex\installation\miktex\bin\x64\
C:\Program Files (x86)\Skype\Phone\
C:\Program Files\MATLAB\R2016b\runtime\win64
C:\Program Files\MATLAB\R2016b\bin
C:\Users\liujianqiao\AppData\Roaming\̑ºüӰӴ\5.0.2.23
C:\Users\liujianqiao\AppData\Local\Microsoft\WindowsApps
E:\Matlab2013\Install\bin\win64


COM server information:
CLSID: {6A239BA0-2DE5-4D03-8B4D-3790D50AC64F}
Program ID: Matlab.Application (Version 9.1)
Command: C:\Program Files\MATLAB\R2016b\bin\win64\MATLAB.exe /MLAutomation

**Comment by xuanxieliu** [comment]
Thank you very much.
I just found there is  something wrong when I change the operating system's path environment variable.
Now I add the MATLAB's bin\win64 directory  to the operating system's path again.
But another problem appear.
After I run /OpenMATLAB[] / ,  an  icon named "mengine(h5fje_shm)   appears on the taskbar. But when I click this icon, it doesn't  appear on the screen. I think it's strange. 
And now I can't get variables from MATLAB workspace.
So I wonder does the strange icon matter?

**Comment by xuanxieliu** [comment]
Here is the the output of MATLink`Developer`GetInfo[] .
MATLink 1.1 for Windows (Fri 15 Aug 2014)

10.2.0 for Microsoft Windows (64-bit) (July 7, 2015)

Force 32-bit engine: False

System PATH:
E:\Wolfram.Mathematica\SystemFiles\Libraries\Windows-x86-64
E:\Wolfram.Mathematica\SystemFiles\Libraries\Windows
E:\Wolfram.Mathematica\SystemFiles\Kernel\Binaries\Windows-x86-64
E:\Wolfram.Mathematica
E:\Wolfram.Mathematica\SystemFiles\FrontEnd\Binaries\Windows-x86-64
E:\Wolfram.Mathematica\SystemFiles\Kernel\Binaries\Windows-x86-64
C:\Program Files (x86)\Intel\iCLS Client\
C:\Program Files\Intel\iCLS Client\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\WiFi\bin\
C:\Program Files\Common Files\Intel\WirelessCommon\
C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin
C:\ProgramData\Lenovo\ReadyApps
E:\LaTex\installation\miktex\bin\x64\
C:\Program Files (x86)\Skype\Phone\
C:\Program Files\MATLAB\R2016b\runtime\win64
C:\Program Files\MATLAB\R2016b\bin
C:\Program Files\MATLAB\R2016b\bin\win64
C:\Users\liujianqiao\AppData\Roaming\̑ºüӰӴ\5.0.2.23
C:\Users\liujianqiao\AppData\Local\Microsoft\WindowsApps
E:\Matlab2013\Install\bin\win64
C:\Program Files\MATLAB\R2016b\bin\win64

COM server information:
CLSID: {6A239BA0-2DE5-4D03-8B4D-3790D50AC64F}
Program ID: Matlab.Application (Version 9.1)
Command: C:\Program Files\MATLAB\R2016b\bin\win64\MATLAB.exe /MLAutomation

**Comment by xuanxieliu** [comment]
Now my problem is not about installing matlink, but connecting to matlab.
When I run /OpenMATLAB[] /, MATLAB workspace does not appear on the screen.
I don't know what's wrong. Hope for your help, Thanks.

**Comment by szhorvat** [comment]
The icon on the taskbar is normal and expected.

MATLink uses a private instance of MATLAB that you cannot access directly.  There will be no MATLAB window.

See the `CommandWindow` function in the documentation on how to show a limited command window: http://matlink.org/documentation/

To connect to an already running MATLAB, follow the instructions here:

http://mathematica.stackexchange.com/a/69937/12

**Comment by xuanxieliu** [comment]
Thank you very much.  MATLink is an amazing  software.
