### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alqahtah** [rsmenon/MATLink#97]
Dear

After installing the package. I type OpenMatlab[] and get the following error.

SetDirectory::cdir: Cannot set current directory to /Users/Retina/Library/Mathematica/Applications/Engine/src.

MATLink`Developer`CompileMEngine::failed: Automatically compiling the MATLink Engine has failed. See http://matlink.org/troubleshooting/, then try to compile it manually and ensure that the path to the MATLAB directory is set correctly in the makefile.

Below is the info:

MATLink 1.1 for MacOSX (Fri 15 Aug 2014)

11.2.0 for Mac OS X x86 (64-bit) (September 11, 2017)

csh:
/bin/csh

MATLAB:
/Applications/MATLAB_R2015b.app

**Comment by szhorvat** [comment]
Where did you download MATLink from?

How did you install it?  Did you follow the instructions carefully? Did you place it in `$UserBaseDirectory/Applications` ?

**Comment by alqahtah** [comment]
Where did you download MATLink from?
I downloaded it from www.matlink.org

How did you install it? Did you follow the instructions carefully? Did you place it in $UserBaseDirectory/Applications ?

I installed it using the install button in Mathematica
Yes, I placed it inside the Applications.

thanks

**Comment by szhorvat** [comment]
I am not aware of any install buttons in Mathematica.  Do you mean the File -> Install menu command?  If so, please remove MATLink and try installing again according to the instructions on matlink.org.  I do not remember what File -> Install does precisely.

As a reminder, extract the zip file and move the MATLink directory into the directory opened by

    SystemOpen@FileNameJoin[{$UserBaseDirectory, "Applications"}]

If it still doesn't work, tell us the output of

    FindFile["MATLink`"]
    Needs["MATLink`"]
    MATLink`Developer`GetInfo[]

when run right after restarting Mathematica.

**Comment by alqahtah** [comment]
Many thankssss. Now it is working like charm.  It seems that I was not following what is documented there.

I really appreciate your help.

Thanks

**Comment by szhorvat** [comment]
Glad it's solved!

**Comment by alqahtah** [comment]
One last question:
I have matlab code that finds complex zeros of any function. I have a complicated function written in Mathematica. The question: is there a way in Matlink enabling me to use the matlab code (calculating zeros) of function written in Mathematica? I am sorry if I am not clear enough. 

Thanks for help.

**Comment by szhorvat** [comment]
The current version does not make this possible.

It is possible to call MATLAB from Mathematica, but it is not, at this moment, possible to call back from MATLAB to Mathematica.

**Comment by alqahtah** [comment]
Thanks for clarification. I think this feature if possible will be a great addition to Matlink.

**Comment by szhorvat** [comment]
Indeed, it is something we have been thinking about. Unfortunately, at this time I do not have enough free time or enough personal need for MATLink to implement it (or even to implement the higher priority performance improvements).
