### ISSUE TITLE
 function Mathematica to Matlab

### ISSUE THREAD

**Issue by anilkumarpmnair** [rsmenon/MATLink#99]
Like transforming variable in Mathematica and send it back to MATLAB via MSet, is there any way to call functions in Mathematica to Matlab?

MFunction is to call the function from MATLAB, which is not available in Mathematica, But  I need the reverse one ( function in Mathematica to Matlab). 
Thanks

**Comment by szhorvat** [comment]
No, MATLink does not currently support calling Mathematica functions from MATLAB.

Its primary purpose is to access MATLAB from within Mathematica, not the reverse.

**Comment by szhorvat** [comment]
That said, this feature would clearly be useful even when working only in Mathematica: it would allow for callbacks, e.g. use MATLAB's numerical integration routines with a function defined in Mathematica.  It is certainly not ruled out for future versions, but it is not available in the current one.

**Comment by anilkumarpmnair** [comment]
Thank you. Actually, I have defined a function in Mathematica.
And using Matlink I am using one script from Matlab in the notebook. I want to call the earlier defined function in that section.

Thanks for the help.

**Comment by szhorvat** [comment]
As I said, it is not currently possible. Please do not open new issues for the same topic.
